force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <displayFormat>Bus-{0}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Air_conditioner__c.field-meta.xml
<CustomField>
    <fullName>Air_conditioner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air conditioner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
            <value>
                <fullName>Ready For Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    public static List<Bus__c> createBus(integer count){
    
    List<Bus__c> allBuses = new  List<Bus__c>();
         for (integer i=1;i<=count;i++){     
       		 Bus__c newbus =  new  Bus__c();
           //  newBus.Name = 'Bus ' + i;
        	 newbus.Air_conditioner__c = true;
        	 newbus.Odometer_Reading__c = 160000;
        	 newbus.Year__c = 2000;
        	 newbus.Maximum_Capacity__c='60';
        	 newbus.Current_Status__c = 'Ready For Use';
             allBuses.add(newbus); 
        }
        
      System.debug(allBuses);
        return allBuses;
    }
}